/*package day14_Exception;

class BBB{public int aaa;

}


class AAA extends BBB{
	public void  catch1(object a) {
		System.out.println("오브젝트 : "+a);
	}
}
public void catch1(int a) {
	System.out.println(a);
}
public void catch1(Object a ) {
	System.out.println("오브젝트 : "+a);
}
public class Ex02 {
	public static void main(String[] args) {
	Object a = new AAA();
	Object ss ="test";
	a.catch(11);
	a.catch("aaaa");
	a.catch(1.111);
	a.catch('a');
	}
}
*/